// Package edge implements FreeSBC's edge plane: a stateful SIP proxy
// between public clients (SIP/UDP, SIP/TCP and SIP/TLS phones and sip.js
// browsers over WS/WSS)
// and one upstream FreeSWITCH, with every media stream anchored through
// the SBC — plain RTP for phones, DTLS-SRTP for browsers.
//
// It is a PROXY, not a B2BUA: Call-ID, From/To tags and CSeq pass through
// untouched, dialogs belong to the endpoints, and FreeSBC stays on the
// signaling path by Record-Route rather than by owning two dialogs. That
// is what makes FreeSWITCH the authoritative registrar — REGISTER and its
// digest challenge are forwarded verbatim, and FreeSBC never holds a
// credential.
package edge

import (
	"hash/fnv"
	"net"
	"net/netip"
	"sort"
	"strings"

	"github.com/emiago/sipgo/sip"

	"github.com/freesbc/freesbc/internal/config"
	fsip "github.com/freesbc/freesbc/internal/sip"
)

// plane is one of the two network sides the proxy straddles.
type plane int

const (
	planePublic plane = iota
	planePrivate
)

// side is everything needed to put a message on one plane: the address
// FreeSBC advertises there (Via sent-by, Contact, Record-Route) and the
// local socket the message must leave from.
//
// The local socket matters as much as the advertised address. A request
// toward a UDP phone must leave from the public listener the phone's NAT
// pinhole points at, and a request toward FreeSWITCH must leave from the
// private socket FreeSWITCH sends its own traffic to — otherwise responses
// come back to a socket nothing is listening on, or arrive from an address
// the far side does not recognise.
type side struct {
	plane     plane
	transport string // "udp", "tcp", "tls", "ws" or "wss"
	advIP     netip.Addr
	advPort   int
	// laddr pins the outbound socket (see sipgo
	// TransportLayer.ClientRequestConnection: a request whose Laddr names
	// a bound listener reuses that listener's connection). It is left zero
	// for tcp/tls/ws/wss, where the connection is found by the client's
	// remote address instead — a stream connection is inbound-only (FreeSBC
	// never dials a client, RFC 5626 flow semantics), so there is exactly
	// one connection per client and it is already in the pool.
	laddr sip.Addr
}

// uri is the SBC's own URI on this side, as it appears in Record-Route,
// Via sent-by and Contact.
func (s side) uri() sip.Uri {
	u := sip.Uri{Host: s.advIP.String(), Port: s.advPort}
	if s.transport != "udp" {
		u.UriParams = sip.NewParams()
		u.UriParams.Add("transport", s.transport)
	}
	return u
}

// recordRoute is the loose-routing Record-Route value for this side.
func (s side) recordRoute() *sip.RecordRouteHeader {
	params := sip.NewParams()
	if s.transport != "udp" {
		params.Add("transport", s.transport)
	}
	params.Add("lr", "")
	return &sip.RecordRouteHeader{
		Address: sip.Uri{Host: s.advIP.String(), Port: s.advPort, UriParams: params},
	}
}

// via builds the Via header FreeSBC adds when forwarding onto this side.
// The branch is generated by the caller so it can be correlated.
//
// rport is requested on UDP only: it asks the next hop to report the
// source port it actually saw, which is what lets responses traverse the
// NAT a phone sits behind (RFC 3581). On WS there is no NAT to traverse —
// the connection is the path.
func (s side) via(branch string) *sip.ViaHeader {
	v := &sip.ViaHeader{
		ProtocolName:    "SIP",
		ProtocolVersion: "2.0",
		Transport:       strings.ToUpper(s.transport),
		Host:            s.advIP.String(),
		Port:            s.advPort,
		Params:          sip.NewParams(),
	}
	v.Params.Add("branch", branch)
	if s.transport == "udp" {
		v.Params.Add("rport", "")
	}
	return v
}

// endpoint is one switch node FreeSBC dials. addr is the signaling
// address (edge.switch entry), host the same as "IP:port", which is what
// the forwarder puts in Destination and what the call table records as a
// remote. carrierPort is the port carrier-originated traffic is delivered
// to on this node (edge.switch_carrier_port, else addr's port).
type endpoint struct {
	addr        netip.AddrPort
	host        string
	carrierPort uint16
}

// carrierAddr is where carrier traffic for this node goes.
func (e endpoint) carrierAddr() netip.AddrPort {
	return netip.AddrPortFrom(e.addr.Addr(), e.carrierPort)
}

// topology is the resolved network model the proxy runs with: an
// IMMUTABLE snapshot, built once at startup from the config and never
// written again. Listener addresses cannot be changed under a running
// socket, so nothing is re-read per request, and nothing needs a lock —
// it is fully constructed in New, before any goroutine that can read it exists.
type topology struct {
	// public holds one side per enabled public transport.
	public map[string]side
	// private is the single FreeSWITCH-facing side.
	private side

	// upstreams is the switch node set, keyed by the node's "IP:port",
	// which is also the name the cooldown table and the logs use.
	// upstreamNames is the same set's names, sorted once here: hashing and
	// failover order must be deterministic, and Go map iteration is not.
	upstreams     map[string]endpoint
	upstreamNames []string

	// media advertised addresses.
	publicMediaIP  netip.Addr
	privateMediaIP netip.Addr
}

// buildTopology resolves the config into the runtime model. priv is the
// private socket (private.ip:5060 unless a test overrides it). It performs
// no DNS: every switch node is a literal address, so a poisoned resolver
// can never redirect the private leg.
func buildTopology(cfg *config.Config, priv netip.AddrPort) *topology {
	upstreams := map[string]endpoint{}
	for _, ap := range cfg.Switches() {
		cp := uint16(cfg.Edge.SwitchCarrierPort)
		if cp == 0 {
			cp = ap.Port()
		}
		upstreams[ap.String()] = endpoint{addr: ap, host: ap.String(), carrierPort: cp}
	}
	// Sorted once, here: the hash pool and the failover order are read from
	// this slice on the request path, where map iteration order must never
	// leak into routing decisions.
	upstreamNames := make([]string, 0, len(upstreams))
	for name := range upstreams {
		upstreamNames = append(upstreamNames, name)
	}
	sort.Strings(upstreamNames)

	t := &topology{
		public:        map[string]side{},
		upstreams:     upstreams,
		upstreamNames: upstreamNames,
		private: side{
			plane:     planePrivate,
			transport: "udp",
			advIP:     priv.Addr(),
			advPort:   int(priv.Port()),
			laddr:     sipAddr(priv.Addr(), int(priv.Port())),
		},
		publicMediaIP:  cfg.PublicIP(),
		privateMediaIP: priv.Addr(),
	}
	pubIP, bind := cfg.PublicIP(), cfg.PublicBind()
	for _, l := range []struct {
		transport string
		port      int
	}{{"udp", cfg.Edge.Listen.UDP}, {"tcp", cfg.Edge.Listen.TCP}, {"tls", cfg.Edge.Listen.TLS},
		{"ws", cfg.Edge.Listen.WS}, {"wss", cfg.Edge.Listen.WSS}} {
		if l.port == 0 {
			continue
		}
		// Public listeners advertise the port they bind. A port
		// translation in front of FreeSBC would need its own config field;
		// there is deliberately none rather than a guess.
		s := side{plane: planePublic, transport: l.transport, advIP: pubIP, advPort: l.port}
		if l.transport == "udp" {
			s.laddr = sipAddr(bind, l.port)
		}
		t.public[l.transport] = s
	}
	return t
}

// sipAddr is the sipgo local-address pin for a bound UDP socket. Every bind
// is a specific address (no wildcards), so the configured address is the
// socket's real local address, which is the key sipgo's connection pool
// uses.
func sipAddr(ip netip.Addr, port int) sip.Addr {
	return sip.Addr{IP: net.IP(ip.AsSlice()), Port: port}
}

// publicSide returns the side for a client transport, falling back to the
// UDP side when the exact transport is not configured.
func (t *topology) publicSide(transport string) (side, bool) {
	transport = strings.ToLower(transport)
	if s, ok := t.public[transport]; ok {
		return s, true
	}
	return side{}, false
}

// isSelf reports whether a URI names one of FreeSBC's own signaling
// addresses. It is how the proxy recognises its own Record-Route values
// coming back as Route headers, and how it detects a loop.
//
// Only the host and port are compared; parameters are not, because a
// downstream element may legitimately add or reorder them.
func (t *topology) isSelf(u sip.Uri) bool {
	ip, err := netip.ParseAddr(u.Host)
	if err != nil {
		return false
	}
	ip = ip.Unmap()
	match := func(s side) bool {
		port := u.Port
		if port == 0 {
			port = 5060
		}
		return s.advIP == ip && s.advPort == port
	}
	if match(t.private) {
		return true
	}
	for _, s := range t.public {
		if match(s) {
			return true
		}
	}
	return false
}

// isSelfVia reports whether a Via header names one of FreeSBC's own
// signaling addresses. RFC 3261 §16.7 step 3 requires a proxy to check
// this before removing the top Via from a response — popping blindly
// destroys the requester's own Via whenever the far end sends a response
// that does not carry the full stack, which is not hypothetical: sofia's
// 100 Trying carries only the topmost Via.
func (t *topology) isSelfVia(v *sip.ViaHeader) bool {
	if v == nil {
		return false
	}
	ip, err := netip.ParseAddr(v.Host)
	if err != nil {
		return false
	}
	ip = ip.Unmap()
	port := v.Port
	if port == 0 {
		port = fsip.DefaultPort(v.Transport)
	}
	if t.private.advIP == ip && t.private.advPort == port {
		return true
	}
	for _, s := range t.public {
		if s.advIP == ip && s.advPort == port {
			return true
		}
	}
	return false
}

// fromUpstream reports whether a datagram's transport source address is one
// of the FreeSWITCHes in the upstream pool. It is NOT a trust decision on
// its own: an address is forgeable and a public listener can be sent
// anything. It is only the source-IP gate the read filter applies on the
// TRUSTED private bind, where the local
// socket has already made the datagram FreeSWITCH-facing and this merely
// keeps every other host out. Never a Via or From host, which the sender
// controls.
//
// Membership is by IP across the WHOLE pool, not by a single address: with
// several switches, any of them may source a request, and the gate must
// not depend on which one. Only the IP is
// compared, not the port: FreeSWITCH may source a request from an
// ephemeral port while still listening on its configured one. Two nodes
// behind one IP are therefore indistinguishable for trust purposes — fine,
// they are equally trusted; per-node precision lives in the dial order and
// the call table's PrivateRemote, which are addr:port.
func (t *topology) fromUpstream(src netip.Addr) bool {
	src = src.Unmap()
	for _, name := range t.upstreamNames {
		if t.upstreams[name].addr.Addr().Unmap() == src {
			return true
		}
	}
	return false
}

// upstreamEntryFor returns the resolved endpoint for a node name. Every
// name a dial order produces comes from t.upstreamNames, which is exactly
// this map's key set, so an unknown name is not a case callers have to
// handle — it cannot occur.
func (t *topology) upstreamEntryFor(name string) endpoint { return t.upstreams[name] }

// hashUpstreamUser maps a SIP user to a hash value: FNV-1a 64 over the
// LOWER-CASED user part. Lower-casing is part of the contract, not a
// nicety — SIP user parts are case-insensitive, and a phone that REGISTERs
// as "Alice" and then calls as "alice" must reach the switch that holds its
// binding. The function is pure (no map iteration, no randomness) so every
// request a user causes, plus any later re-computation such as
// directionFor's race-ACK fallback, agrees on the node with no shared
// state.
func hashUpstreamUser(user string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(strings.ToLower(user)))
	return h.Sum64()
}

// upstreamDialOrder is the failover order for a user: the hash-chosen node
// first, then the rest of the pool in rotation from it, then any cooled
// nodes.
//
// The hash pool EXCLUDES cooled nodes whenever at least one node is
// available (D6): leaving a sick node in the pool would keep routing it its
// share of the users, which is the opposite of what a passive penalty is
// for. It falls back to the full sorted set when everything is cooling — a
// cooldown must never make the proxy refuse to try anything at all.
//
// available reports whether a node may be used. In production it is the
// cooldown table; tests pass a plain function.
func (t *topology) upstreamDialOrder(user string, available func(string) bool) []string {
	if len(t.upstreamNames) == 0 {
		return nil
	}
	pool, cooled := orderByAvailability(t.upstreamNames, available)
	idx := int(hashUpstreamUser(user) % uint64(len(pool)))
	order := make([]string, 0, len(pool)+len(cooled))
	order = append(order, pool[idx:]...)
	order = append(order, pool[:idx]...)
	order = append(order, cooled...)
	return order
}

// selectUpstream picks the node a user's request should start on: the head
// of its dial order. ok is false only for an empty pool, which validation
// makes impossible on a running proxy.
func (t *topology) selectUpstream(user string, available func(string) bool) (string, endpoint, bool) {
	order := t.upstreamDialOrder(user, available)
	if len(order) == 0 {
		return "", endpoint{}, false
	}
	return order[0], t.upstreams[order[0]], true
}

// orderByAvailability splits names into the ones the cooldown oracle says
// may be used and the ones still cooling, preserving the input order.
//
// When EVERY name is cooling it returns the whole set as available: a
// cooldown is a suspicion, not a verdict, and a hard block would turn one
// sick target into a dead route. The upstream pool partitions its candidates this way.
func orderByAvailability(names []string, available func(string) bool) (pool, cooled []string) {
	for _, name := range names {
		if available(name) {
			pool = append(pool, name)
		} else {
			cooled = append(cooled, name)
		}
	}
	if len(pool) == 0 {
		return names, nil
	}
	return pool, cooled
}

// upstreamOrder is a user's failover order with the passive cooldown table
// as the availability oracle: the production binding of upstreamDialOrder.
func (s *Server) upstreamOrder(user string) []string {
	return s.topo.upstreamDialOrder(user, s.upstreamCooldown.Available)
}

// selectUpstream is a user's hash-chosen node, cooldown-aware (see
// topology.selectUpstream).
func (s *Server) selectUpstream(user string) (string, endpoint, bool) {
	return s.topo.selectUpstream(user, s.upstreamCooldown.Available)
}
