package app

import (
	"bufio"
	"context"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"net/netip"
	"os"
	"strconv"
	"strings"

	"golang.org/x/crypto/bcrypt"

	"github.com/freesbc/freesbc/internal/config"
)

// PublicIPService is the echo service `freesbc init` asks for the public
// address. It is named in every notice printed before the lookup.
const PublicIPService = "https://api.ipify.org"

// adminListen is the loopback address init writes for the admin API.
const adminListen = "127.0.0.1:8080"

// adminBcryptCost satisfies the admin.password_hash minimum (10).
const adminBcryptCost = 10

// InitOptions drives Init. Everything environment-dependent is a field, so
// tests run without a terminal, a network or a local interface.
type InitOptions struct {
	// Path is the file to create; it must not exist.
	Path string

	// Explicit values (flag, then env, resolved by the caller). Empty or
	// zero means "detect, or ask".
	Switch     string // IP:port, or a bare IP (port 5060)
	PrivateIP  string
	PublicIP   string
	PublicBind string
	UDPPort    int

	// NoPublicLookup skips every network lookup of the public address.
	NoPublicLookup bool

	// Interactive asks for each value that was not given explicitly. It must
	// be true only when In is a terminal.
	Interactive bool
	In          io.Reader
	Out         io.Writer // prompts and the final hint
	Err         io.Writer // notices, including the one before a lookup

	// ReadPassword reads one line without echo (interactive admin prompt).
	ReadPassword func() (string, error)

	// Detectors.
	PrivateIPToward func(sw netip.AddrPort) (netip.Addr, error)
	DefaultRouteIP  func() (netip.Addr, error)
	LookupPublicIP  func(ctx context.Context) (netip.Addr, error)
}

// ErrInitFileExists is returned when the target file is already there.
var ErrInitFileExists = errors.New("already exists; refusing to overwrite")

// HashAdminPassword returns a bcrypt hash that satisfies the
// admin.password_hash rule (cost >= 10).
func HashAdminPassword(password string) (string, error) {
	h, err := bcrypt.GenerateFromPassword([]byte(password), adminBcryptCost)
	if err != nil {
		return "", err
	}
	return string(h), nil
}

// Init writes a minimal, valid config to o.Path. Nothing is written unless
// the generated bytes pass config.Parse, the same validation as `check`.
func Init(ctx context.Context, o InitOptions) error {
	if o.Path == "" {
		return errors.New("init: no config path")
	}
	if o.Out == nil {
		o.Out = io.Discard
	}
	if o.Err == nil {
		o.Err = io.Discard
	}
	// Refuse before asking anything, so nobody answers prompts for nothing.
	if _, err := os.Lstat(o.Path); err == nil {
		return fmt.Errorf("%s %w", o.Path, ErrInitFileExists)
	} else if !errors.Is(err, fs.ErrNotExist) {
		return fmt.Errorf("init: %w", err)
	}
	p := &prompter{out: o.Out}
	if o.Interactive {
		if o.In == nil {
			return errors.New("init: interactive mode needs an input")
		}
		p.in = bufio.NewReader(o.In)
	}

	// edge.switch (asked first, no default).
	swText := o.Switch
	if swText == "" {
		if !o.Interactive {
			return errors.New("init: the switch address is required: pass --switch IP[:port] or set FREESBC_SWITCH")
		}
		var err error
		if swText, err = p.ask("edge.switch (the SIP switch, IP[:port])", ""); err != nil {
			return err
		}
	}
	sw, err := parseSwitch(swText)
	if err != nil {
		return err
	}

	// private.ip: the local address that routes to the switch.
	privText := o.PrivateIP
	if privText == "" {
		def := ""
		if o.PrivateIPToward != nil {
			if a, derr := o.PrivateIPToward(sw); derr == nil && a.IsValid() {
				def = a.String()
			}
		}
		if privText, err = p.value(o.Interactive, "private.ip (faces the switch)", def, "private.ip: could not be detected; pass --private-ip"); err != nil {
			return err
		}
	}
	priv, err := parseIP("private.ip", privText)
	if err != nil {
		return err
	}

	// public.bind: the local address toward the default route. Empty means
	// "same as public.ip" and is settled below.
	bindText := o.PublicBind
	if bindText == "" {
		def := ""
		if o.DefaultRouteIP != nil {
			if a, derr := o.DefaultRouteIP(); derr == nil && a.IsValid() {
				def = a.String()
			}
		}
		if o.Interactive {
			if bindText, err = p.ask("public.bind (local address of the public socket)", def); err != nil {
				return err
			}
		} else {
			bindText = def
		}
	}

	// public.ip: explicit, else the echo service, else public.bind.
	ipText := o.PublicIP
	if ipText == "" {
		def := ""
		if !o.NoPublicLookup && o.LookupPublicIP != nil {
			look := true
			if o.Interactive {
				look, err = p.confirm("Look up public IP via " + strings.TrimPrefix(PublicIPService, "https://") + "?")
				if err != nil {
					return err
				}
			}
			if look {
				fmt.Fprintf(o.Err, "public.ip: asking %s (skip with --no-public-lookup or --public-ip)\n", PublicIPService)
				if a, lerr := o.LookupPublicIP(ctx); lerr == nil && a.IsValid() {
					def = a.String()
				} else {
					fmt.Fprintf(o.Err, "public.ip: lookup failed (%v)\n", lerr)
				}
			}
		}
		if def == "" && bindText != "" {
			def = bindText
			fmt.Fprintf(o.Err, "public.ip: no address found, using public.bind %s (a host with a direct public IP)\n", bindText)
		}
		if ipText, err = p.value(o.Interactive, "public.ip (advertised to phones and carriers)", def, "public.ip: could not be detected; pass --public-ip"); err != nil {
			return err
		}
	}
	pub, err := parseIP("public.ip", ipText)
	if err != nil {
		return err
	}
	bind := pub
	if bindText != "" {
		if bind, err = parseIP("public.bind", bindText); err != nil {
			return err
		}
	}
	if priv == bind {
		return fmt.Errorf("init: private.ip and public.bind are both %s: FreeSBC needs two addresses, one facing the switch and one facing the internet; add a second IP or NIC (or a VLAN or loopback alias for the private side)", priv)
	}

	port := o.UDPPort
	if port == 0 {
		port = 5060
		if o.Interactive {
			t, perr := p.ask("edge.listen.udp (public SIP UDP port)", "5060")
			if perr != nil {
				return perr
			}
			if port, err = strconv.Atoi(t); err != nil {
				return fmt.Errorf("init: udp port %q is not a number", t)
			}
		}
	}
	if port < 1 || port > 65535 {
		return fmt.Errorf("init: udp port %d is out of range", port)
	}

	// admin (interactive only; a password never travels in a flag or env).
	hash := ""
	if o.Interactive {
		if hash, err = o.askAdmin(); err != nil {
			return err
		}
	}

	data := renderInitConfig(pub, bind, priv, sw, port, hash)
	if _, err := config.Parse(data); err != nil {
		return fmt.Errorf("init: generated config is invalid, nothing written: %w", err)
	}
	f, err := os.OpenFile(o.Path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if err != nil {
		if errors.Is(err, fs.ErrExist) {
			return fmt.Errorf("%s %w", o.Path, ErrInitFileExists)
		}
		return fmt.Errorf("init: %w", err)
	}
	if _, err := f.Write(data); err != nil {
		f.Close()
		os.Remove(o.Path)
		return fmt.Errorf("init: write %s: %w", o.Path, err)
	}
	if err := f.Close(); err != nil {
		os.Remove(o.Path)
		return fmt.Errorf("init: write %s: %w", o.Path, err)
	}
	fmt.Fprintf(o.Out, "wrote %s\nnext: freesbc check -c %s, then freesbc run -c %s\nThe switch side (accepting traffic from %s) is described in docs/edge.md.\n",
		o.Path, o.Path, o.Path, priv)
	return nil
}

// askAdmin prompts for the admin password and returns its bcrypt hash, or ""
// when the answer is empty.
func (o InitOptions) askAdmin() (string, error) {
	if o.ReadPassword == nil {
		return "", nil
	}
	fmt.Fprint(o.Out, "admin password (Enter = no admin section): ")
	pw, err := o.ReadPassword()
	fmt.Fprintln(o.Out)
	if err != nil {
		return "", fmt.Errorf("init: read password: %w", err)
	}
	if pw == "" {
		return "", nil
	}
	fmt.Fprint(o.Out, "confirm admin password: ")
	again, err := o.ReadPassword()
	fmt.Fprintln(o.Out)
	if err != nil {
		return "", fmt.Errorf("init: read password: %w", err)
	}
	if again != pw {
		return "", errors.New("init: the admin passwords do not match")
	}
	h, err := HashAdminPassword(pw)
	if err != nil {
		return "", fmt.Errorf("init: hash admin password: %w", err)
	}
	return h, nil
}

// renderInitConfig builds the file. public.bind is omitted when it equals
// public.ip; the admin section is omitted without a hash.
func renderInitConfig(pub, bind, priv netip.Addr, sw netip.AddrPort, udp int, adminHash string) []byte {
	var b strings.Builder
	b.WriteString("# Generated by `freesbc init`. Every key is documented in docs/config.md;\n")
	b.WriteString("# freesbc.example.yaml shows the optional ones (carriers, TLS, WebRTC).\n\n")
	fmt.Fprintf(&b, "public:\n  ip: %s\n", pub)
	if bind != pub {
		fmt.Fprintf(&b, "  bind: %s\n", bind)
	}
	fmt.Fprintf(&b, "\nprivate:\n  ip: %s\n", priv)
	fmt.Fprintf(&b, "\nedge:\n  switch: [%q]\n  listen:\n    udp: %d\n", sw.String(), udp)
	if adminHash != "" {
		fmt.Fprintf(&b, "\nadmin:\n  listen: %s\n  password_hash: %q\n", adminListen, adminHash)
	}
	return []byte(b.String())
}

// parseSwitch accepts IP:port or a bare IP (port 5060).
func parseSwitch(s string) (netip.AddrPort, error) {
	s = strings.TrimSpace(s)
	if ap, err := netip.ParseAddrPort(s); err == nil {
		return ap, nil
	}
	if a, err := netip.ParseAddr(s); err == nil {
		return netip.AddrPortFrom(a, 5060), nil
	}
	return netip.AddrPort{}, fmt.Errorf("init: edge.switch %q is not a literal IP or IP:port (hostnames are not resolved)", s)
}

func parseIP(key, s string) (netip.Addr, error) {
	a, err := netip.ParseAddr(strings.TrimSpace(s))
	if err != nil {
		return netip.Addr{}, fmt.Errorf("init: %s %q is not an IP address", key, s)
	}
	return a.Unmap(), nil
}

// prompter asks questions on out and reads answers from in (nil when not
// interactive).
type prompter struct {
	out io.Writer
	in  *bufio.Reader
}

// ask prints "label [def]: " and returns the trimmed answer, def on Enter.
func (p *prompter) ask(label, def string) (string, error) {
	if def != "" {
		fmt.Fprintf(p.out, "%s [%s]: ", label, def)
	} else {
		fmt.Fprintf(p.out, "%s: ", label)
	}
	line, err := p.in.ReadString('\n')
	if err != nil && (!errors.Is(err, io.EOF) || line == "") {
		if errors.Is(err, io.EOF) && def != "" {
			fmt.Fprintln(p.out)
			return def, nil
		}
		return "", fmt.Errorf("init: reading answer: %w", err)
	}
	if line = strings.TrimSpace(line); line != "" {
		return line, nil
	}
	return def, nil
}

// confirm asks a Y/n question; Enter means yes.
func (p *prompter) confirm(label string) (bool, error) {
	fmt.Fprintf(p.out, "%s [Y/n]: ", label)
	line, err := p.in.ReadString('\n')
	if err != nil && (!errors.Is(err, io.EOF) || line == "") {
		return false, fmt.Errorf("init: reading answer: %w", err)
	}
	switch strings.ToLower(strings.TrimSpace(line)) {
	case "", "y", "yes":
		return true, nil
	}
	return false, nil
}

// value resolves one setting: asked when interactive, else the detected
// default; with neither it fails with missing.
func (p *prompter) value(interactive bool, label, def, missing string) (string, error) {
	v := def
	if interactive {
		var err error
		if v, err = p.ask(label, def); err != nil {
			return "", err
		}
	}
	if v == "" {
		return "", errors.New("init: " + missing)
	}
	return v, nil
}
