// Package proxy implements FreeSBC's edge plane: a stateful SIP proxy
// between public clients (SIP/UDP phones and sip.js browsers over WS/WSS)
// and one upstream FreeSWITCH, with every media stream anchored through
// the SBC — plain RTP for phones, DTLS-SRTP for browsers.
//
// It is a PROXY, not a B2BUA: Call-ID, From/To tags and CSeq pass through
// untouched, dialogs belong to the endpoints, and FreeSBC stays on the
// signaling path by Record-Route rather than by owning two dialogs. That
// is what makes FreeSWITCH the authoritative registrar — REGISTER and its
// digest challenge are forwarded verbatim, and FreeSBC never holds a
// credential.
//
// It runs alongside, and entirely independently of, the trunk B2BUA in
// package trunk: a separate sipgo user agent, separate listeners, separate
// media pools. Neither plane can disturb the other, and a deployment may
// enable either or both.
package proxy

import (
	"hash/fnv"
	"net"
	"net/netip"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"

	"github.com/emiago/sipgo/sip"

	"github.com/freesbc/freesbc/internal/config"
)

// plane is one of the two network sides the proxy straddles.
type plane int

const (
	planePublic plane = iota
	planePrivate
)

func (p plane) String() string {
	if p == planePublic {
		return "public"
	}
	return "private"
}

// side is everything needed to put a message on one plane: the address
// FreeSBC advertises there (Via sent-by, Contact, Record-Route) and the
// local socket the message must leave from.
//
// The local socket matters as much as the advertised address. A request
// toward a UDP phone must leave from the public listener the phone's NAT
// pinhole points at, and a request toward FreeSWITCH must leave from the
// private socket FreeSWITCH sends its own traffic to — otherwise responses
// come back to a socket nothing is listening on, or arrive from an address
// the far side does not recognise.
type side struct {
	plane     plane
	transport string // "udp", "ws" or "wss"
	advIP     netip.Addr
	advPort   int
	// laddr pins the outbound socket (see sipgo
	// TransportLayer.ClientRequestConnection: a request whose Laddr names
	// a bound listener reuses that listener's connection). It is left zero
	// for ws/wss, where the connection is found by the client's remote
	// address instead — a WebSocket is inbound-only, so there is exactly
	// one connection per client and it is already in the pool.
	laddr sip.Addr
}

// uri is the SBC's own URI on this side, as it appears in Record-Route,
// Via sent-by and Contact.
func (s side) uri() sip.Uri {
	u := sip.Uri{Host: s.advIP.String(), Port: s.advPort}
	if s.transport != "udp" {
		u.UriParams = sip.NewParams()
		u.UriParams.Add("transport", s.transport)
	}
	return u
}

// recordRoute is the loose-routing Record-Route value for this side.
func (s side) recordRoute() *sip.RecordRouteHeader {
	params := sip.NewParams()
	if s.transport != "udp" {
		params.Add("transport", s.transport)
	}
	params.Add("lr", "")
	return &sip.RecordRouteHeader{
		Address: sip.Uri{Host: s.advIP.String(), Port: s.advPort, UriParams: params},
	}
}

// via builds the Via header FreeSBC adds when forwarding onto this side.
// The branch is generated by the caller so it can be correlated.
//
// rport is requested on UDP only: it asks the next hop to report the
// source port it actually saw, which is what lets responses traverse the
// NAT a phone sits behind (RFC 3581). On WS there is no NAT to traverse —
// the connection is the path.
func (s side) via(branch string) *sip.ViaHeader {
	v := &sip.ViaHeader{
		ProtocolName:    "SIP",
		ProtocolVersion: "2.0",
		Transport:       strings.ToUpper(s.transport),
		Host:            s.advIP.String(),
		Port:            s.advPort,
		Params:          sip.NewParams(),
	}
	v.Params.Add("branch", branch)
	if s.transport == "udp" {
		v.Params.Add("rport", "")
	}
	return v
}

// upstreamEntry is one resolved FreeSWITCH upstream: its signaling address
// (parsed) plus the host:port as configured, which is what the forwarder
// puts in Destination and what the call table records as PrivateRemote.
type upstreamEntry struct {
	addr netip.AddrPort
	host string
}

// pstnGateway is one resolved carrier gateway: its signaling address
// (parsed) plus the host:port as configured, which is what the forwarder
// puts in Destination.
type pstnGateway struct {
	addr netip.AddrPort
	host string
}

// pstnRoute is one resolved routing rule: which gateways a called number
// fails over across, in order. A nil re matches every number — that is the
// catch-all a number with no more specific prefix rule falls back to.
type pstnRoute struct {
	re      *regexp.Regexp
	targets []string // gateway names, in failover order
}

// pstnTopo is the resolved PSTN gateway model. match is the host:port
// FreeSWITCH bridges PSTN calls to — the trigger of the classification in
// onInvite; gateways is keyed by the names routes reference; routes is the
// per-number failover plan, in evaluation order. The v1 alias shape
// (config address + match) converges on this same model at build time as
// gateway "default" with one catch-all route, so the request path never
// knows which config shape produced it.
type pstnTopo struct {
	match    config.HostPort
	gateways map[string]pstnGateway
	routes   []pstnRoute
}

// pstnEnabled reports whether a PSTN trunk is configured. A config without
// sip.pstn leaves the gateways map nil; validation guarantees a configured
// trunk always has at least one gateway.
func (t *topology) pstnEnabled() bool { return len(t.pstn.gateways) > 0 }

// resolvePSTNRoute picks the failover list for a called number: the first
// route whose regexp matches the number wins, a nil regexp matches every
// number, and no match means the call is not a PSTN call at all. Pure and
// stateless, mirroring the trunk plane's route resolution.
func resolvePSTNRoute(routes []pstnRoute, user string) ([]string, bool) {
	for _, r := range routes {
		if r.re == nil || r.re.MatchString(user) {
			return r.targets, true
		}
	}
	return nil, false
}

// topology is the resolved network model the proxy runs with, built once
// at startup from the config. Listener addresses cannot be changed under a
// running socket, so this is deliberately a snapshot rather than something
// re-read per request. The only post-build adjustment is that each UDP
// side's outbound pin is re-pointed at its bound socket's actual local
// address when Run opens the sockets (a wildcard bind does not come up as
// the address written in the config); nothing else is read back from the
// kernel.
type topology struct {
	// mu guards the public map against a write. Production writes the map
	// only at startup, before any request can be handled, so requests take
	// the read lock purely as a formality — except that the wildcard-bind
	// fix (Run.pinOutboundToSockets) and the tests that force its failure
	// mode do re-point a pin at runtime, and the Go memory model gives the
	// request path no other ordering with them. The lock is what keeps that
	// legitimate late write race-free.
	mu sync.RWMutex
	// public holds one side per enabled public transport.
	public map[string]side
	// private is the single FreeSWITCH-facing side.
	private side

	// upstreams is the FreeSWITCH upstream set, keyed by the names the
	// cooldown table and the logs use. The v1 alias (sip.upstream.address)
	// synthesises node "default" at build time, so both config shapes are
	// one runtime model and the request path never knows which produced it.
	// upstreamNames is the same set's names, sorted once here: hashing and
	// failover order must be deterministic, and Go map iteration is not.
	upstreams     map[string]upstreamEntry
	upstreamNames []string

	// pstn is the PSTN trunk, when sip.pstn is configured; a nil gateways
	// map leaves the trunk off. Resolved at startup like upstream — the
	// topology is a snapshot, not something re-read per request (the
	// failure budgets ARE re-read per call from the store, but they are not
	// topology).
	pstn pstnTopo

	// media advertised addresses.
	publicMediaIP  netip.Addr
	privateMediaIP netip.Addr
}

// buildTopology resolves the config into the runtime model. It performs
// no DNS: every upstream node must be a literal address, so a poisoned
// resolver can never redirect the private leg and failover never waits on
// a lookup.
func buildTopology(cfg *config.Config) (*topology, error) {
	// The upstream pool converges the two config shapes here, exactly like
	// sip.pstn below: the v1 alias is synthesised — in buildTopology, NOT in
	// the config defaults — into the multi model as the single node
	// "default", so a v1 config and an equivalent one-node pool behave
	// identically by construction (and the hash degenerates trivially: one
	// node is always index 0). The store keeps what the operator wrote.
	upstreams := map[string]upstreamEntry{}
	resolveUpstream := func(name, label, address string) error {
		host, portStr, err := net.SplitHostPort(address)
		if err != nil {
			return err
		}
		ip, err := netip.ParseAddr(host)
		if err != nil {
			return &configError{label + " must be a literal IP:port, got " + host}
		}
		port, err := strconv.Atoi(portStr)
		if err != nil {
			return err
		}
		upstreams[name] = upstreamEntry{
			addr: netip.AddrPortFrom(ip, uint16(port)),
			host: address,
		}
		return nil
	}
	if cfg.SIP.Upstream.Address != "" {
		if err := resolveUpstream("default", "sip.upstream.address", cfg.SIP.Upstream.Address); err != nil {
			return nil, err
		}
	} else {
		for name, n := range cfg.SIP.Upstreams.Nodes {
			// A node entry missing its address cannot survive validation,
			// but a nil map entry (an empty `fs-1:` block) would panic below
			// — treat it as the address error it is.
			if n == nil || n.Address == "" {
				return nil, &configError{"sip.upstreams.nodes." + name + " must be a literal IP:port, got \"\""}
			}
			if err := resolveUpstream(name, "sip.upstreams.nodes."+name, n.Address); err != nil {
				return nil, err
			}
		}
	}
	// Sorted once, here: the hash pool and the failover order are read from
	// this slice on the request path, where map iteration order must never
	// leak into routing decisions.
	upstreamNames := make([]string, 0, len(upstreams))
	for name := range upstreams {
		upstreamNames = append(upstreamNames, name)
	}
	sort.Strings(upstreamNames)

	// sip.pstn is optional; the resolution mirrors the upstream's: no DNS,
	// literal address only, validated host:port. The match must already be
	// a literal too — it is compared byte-for-byte against Request-URIs,
	// and a name would silently never match (or, worse, match the wrong
	// thing once a resolver changed).
	//
	// The two config shapes converge here. The v1 alias (a single
	// `address`) is synthesised — in buildTopology, NOT in the config
	// defaults — into the multi model: one gateway named "default" plus a
	// catch-all route naming it. The store keeps what the operator wrote;
	// this function is the one place both shapes become one runtime model,
	// so a v1 config and an equivalent multi config behave identically by
	// construction.
	pstn := pstnTopo{gateways: map[string]pstnGateway{}}
	if cfg.SIP.Pstn.Address != "" || len(cfg.SIP.Pstn.Gateways) > 0 {
		if _, err := netip.ParseAddr(cfg.SIP.Pstn.Match.Host); err != nil {
			return nil, &configError{"sip.pstn.match must be a literal IP, got " + cfg.SIP.Pstn.Match.Host}
		}
		pstn.match = cfg.SIP.Pstn.Match

		// Parse one gateway address into the runtime model. A name that
		// must be resolved would make failover depend on DNS at call time —
		// the opposite of the startup snapshot the rest of the topology is.
		resolve := func(name, label, address string) error {
			gwHost, gwPortStr, err := net.SplitHostPort(address)
			if err != nil {
				return err
			}
			gwIP, err := netip.ParseAddr(gwHost)
			if err != nil {
				return &configError{label + " must be a literal IP:port, got " + gwHost}
			}
			gwPort, err := strconv.Atoi(gwPortStr)
			if err != nil {
				return err
			}
			pstn.gateways[name] = pstnGateway{
				addr: netip.AddrPortFrom(gwIP, uint16(gwPort)),
				host: address,
			}
			return nil
		}

		if cfg.SIP.Pstn.Address != "" {
			// v1 alias: the single gateway the config has always meant.
			if err := resolve("default", "sip.pstn.address", cfg.SIP.Pstn.Address); err != nil {
				return nil, err
			}
			pstn.routes = []pstnRoute{{targets: []string{"default"}}}
		} else {
			for name, g := range cfg.SIP.Pstn.Gateways {
				// A gateway entry missing its address cannot survive
				// validation, but a nil map entry (an empty `gw:` block)
				// would panic below — treat it as the address error it is.
				if g == nil || g.Address == "" {
					return nil, &configError{"sip.pstn.gateways." + name + ".address must be a literal IP:port, got \"\""}
				}
				if err := resolve(name, "sip.pstn.gateways."+name, g.Address); err != nil {
					return nil, err
				}
			}
			for _, r := range cfg.SIP.Pstn.Routes {
				// The match was compiled by validation (PstnRoute.matchTo);
				// CompiledMatch() is nil for a catch-all.
				pstn.routes = append(pstn.routes, pstnRoute{re: r.CompiledMatch(), targets: r.To})
			}
		}
	}

	privIP := cfg.PrivateAdvertisedIP()
	t := &topology{
		public:        map[string]side{},
		upstreams:     upstreams,
		upstreamNames: upstreamNames,
		pstn:          pstn,
		private: side{
			plane:     planePrivate,
			transport: "udp",
			advIP:     privIP,
			advPort:   cfg.PrivateSIPAdvertisedPort(),
			laddr: sip.Addr{
				IP:   net.ParseIP(cfg.SIP.Private.Bind.Host),
				Port: cfg.SIP.Private.Bind.Port,
			},
		},
		publicMediaIP:  cfg.PublicRTPAdvertisedIP(),
		privateMediaIP: cfg.PrivateRTPAdvertisedIP(),
	}
	pubIP := cfg.PublicAdvertisedIP()
	for _, l := range cfg.PublicSIPListeners() {
		s := side{
			plane:     planePublic,
			transport: l.Transport,
			advIP:     pubIP,
			// Public listeners advertise the port they bind. A port
			// translation in front of FreeSBC would need its own config
			// field; there is deliberately none yet rather than a guess.
			advPort: l.Bind.Port,
		}
		if l.Transport == "udp" {
			s.laddr = sip.Addr{IP: net.ParseIP(l.Bind.Host), Port: l.Bind.Port}
		}
		t.public[l.Transport] = s
	}
	return t, nil
}

type configError struct{ msg string }

func (e *configError) Error() string { return "proxy: " + e.msg }

// publicSide returns the side for a client transport, falling back to the
// UDP side when the exact transport is not configured.
func (t *topology) publicSide(transport string) (side, bool) {
	t.mu.RLock()
	defer t.mu.RUnlock()
	transport = strings.ToLower(transport)
	if s, ok := t.public[transport]; ok {
		return s, true
	}
	return side{}, false
}

// isSelf reports whether a URI names one of FreeSBC's own signaling
// addresses. It is how the proxy recognises its own Record-Route values
// coming back as Route headers, and how it detects a loop.
//
// Only the host and port are compared; parameters are not, because a
// downstream element may legitimately add or reorder them.
func (t *topology) isSelf(u sip.Uri) bool {
	t.mu.RLock()
	defer t.mu.RUnlock()
	ip, err := netip.ParseAddr(u.Host)
	if err != nil {
		return false
	}
	ip = ip.Unmap()
	match := func(s side) bool {
		port := u.Port
		if port == 0 {
			port = 5060
		}
		return s.advIP == ip && s.advPort == port
	}
	if match(t.private) {
		return true
	}
	for _, s := range t.public {
		if match(s) {
			return true
		}
	}
	return false
}

// isSelfVia reports whether a Via header names one of FreeSBC's own
// signaling addresses. RFC 3261 §16.7 step 3 requires a proxy to check
// this before removing the top Via from a response — popping blindly
// destroys the requester's own Via whenever the far end sends a response
// that does not carry the full stack, which is not hypothetical: sofia's
// 100 Trying carries only the topmost Via.
func (t *topology) isSelfVia(v *sip.ViaHeader) bool {
	t.mu.RLock()
	defer t.mu.RUnlock()
	if v == nil {
		return false
	}
	ip, err := netip.ParseAddr(v.Host)
	if err != nil {
		return false
	}
	ip = ip.Unmap()
	port := v.Port
	if port == 0 {
		port = defaultPort(v.Transport)
	}
	if t.private.advIP == ip && t.private.advPort == port {
		return true
	}
	for _, s := range t.public {
		if s.advIP == ip && s.advPort == port {
			return true
		}
	}
	return false
}

// defaultPort is the conventional port for a transport, used when a Via
// omits one.
func defaultPort(transport string) int {
	switch strings.ToLower(transport) {
	case "tls", "wss":
		return 5061
	case "ws":
		return 80
	default:
		return 5060
	}
}

// fromUpstream reports whether a request arrived from a FreeSWITCH in the
// upstream pool. The transport source address is the only trustworthy
// signal — never a Via or From host, which the sender controls.
//
// Membership is by IP across the WHOLE pool, not by a single address: with
// several switches, any of them may source a request, and the trust
// decision (readFilter, arrivedOnPrivate, the PSTN-bridge classification,
// the shield exemption) must not depend on which one. Only the IP is
// compared, not the port: FreeSWITCH may source a request from an
// ephemeral port while still listening on its configured one. Two nodes
// behind one IP are therefore indistinguishable for trust purposes — fine,
// they are equally trusted; per-node precision lives in the dial order and
// the call table's PrivateRemote, which are addr:port.
func (t *topology) fromUpstream(src netip.Addr) bool {
	src = src.Unmap()
	for _, name := range t.upstreamNames {
		if t.upstreams[name].addr.Addr().Unmap() == src {
			return true
		}
	}
	return false
}

// upstreamEntryFor returns the resolved entry for a node name. ok is false
// only for a name the topology does not know, which a dial order cannot
// produce.
func (t *topology) upstreamEntryFor(name string) (upstreamEntry, bool) {
	e, ok := t.upstreams[name]
	return e, ok
}

// hashUpstreamUser maps a SIP user to a hash value: FNV-1a 64 over the
// LOWER-CASED user part. Lower-casing is part of the contract, not a
// nicety — SIP user parts are case-insensitive, and a phone that REGISTERs
// as "Alice" and then calls as "alice" must reach the switch that holds its
// binding. The function is pure (no map iteration, no randomness) so every
// request a user causes, plus any later re-computation such as
// directionFor's race-ACK fallback, agrees on the node with no shared
// state.
func hashUpstreamUser(user string) uint64 {
	h := fnv.New64a()
	_, _ = h.Write([]byte(strings.ToLower(user)))
	return h.Sum64()
}

// upstreamDialOrder is the failover order for a user: the hash-chosen node
// first, then the rest of the pool in rotation from it, then any cooled
// nodes.
//
// The hash pool EXCLUDES cooled nodes whenever at least one node is
// available (D6): leaving a sick node in the pool would keep routing it its
// share of the users, which is the opposite of what a passive penalty is
// for. It falls back to the full sorted set when everything is cooling — a
// cooldown must never make the proxy refuse to try anything at all.
//
// available reports whether a node may be used. In production it is the
// cooldown table; tests pass a plain function.
func (t *topology) upstreamDialOrder(user string, available func(string) bool) []string {
	pool := make([]string, 0, len(t.upstreamNames))
	var cooled []string
	for _, name := range t.upstreamNames {
		if available == nil || available(name) {
			pool = append(pool, name)
		} else {
			cooled = append(cooled, name)
		}
	}
	if len(pool) == 0 {
		// Everything is cooling: dial the full set rather than nothing.
		pool, cooled = t.upstreamNames, nil
	}
	if len(pool) == 0 {
		return nil
	}
	idx := int(hashUpstreamUser(user) % uint64(len(pool)))
	order := make([]string, 0, len(pool)+len(cooled))
	order = append(order, pool[idx:]...)
	order = append(order, pool[:idx]...)
	order = append(order, cooled...)
	return order
}

// selectUpstream picks the node a user's request should start on: the head
// of its dial order. ok is false only for an empty pool, which validation
// makes impossible on a running proxy.
func (t *topology) selectUpstream(user string, available func(string) bool) (string, upstreamEntry, bool) {
	order := t.upstreamDialOrder(user, available)
	if len(order) == 0 {
		return "", upstreamEntry{}, false
	}
	return order[0], t.upstreams[order[0]], true
}

// upstreamOrder is a user's failover order with the passive cooldown table
// as the availability oracle: the production binding of upstreamDialOrder.
func (s *Server) upstreamOrder(user string) []string {
	return s.topo.upstreamDialOrder(user, s.upstreamCooldown.Available)
}

// selectUpstream is a user's hash-chosen node, cooldown-aware (see
// topology.selectUpstream).
func (s *Server) selectUpstream(user string) (string, upstreamEntry, bool) {
	return s.topo.selectUpstream(user, s.upstreamCooldown.Available)
}
