// Package proxy implements FreeSBC's edge plane: a stateful SIP proxy
// between public clients (SIP/UDP phones and sip.js browsers over WS/WSS)
// and one upstream FreeSWITCH, with every media stream anchored through
// the SBC — plain RTP for phones, DTLS-SRTP for browsers.
//
// It is a PROXY, not a B2BUA: Call-ID, From/To tags and CSeq pass through
// untouched, dialogs belong to the endpoints, and FreeSBC stays on the
// signaling path by Record-Route rather than by owning two dialogs. That
// is what makes FreeSWITCH the authoritative registrar — REGISTER and its
// digest challenge are forwarded verbatim, and FreeSBC never holds a
// credential.
//
// It runs alongside, and entirely independently of, the trunk B2BUA in
// package sig: a separate sipgo user agent, separate listeners, separate
// media pools. Neither plane can disturb the other, and a deployment may
// enable either or both.
package proxy

import (
	"net"
	"net/netip"
	"strconv"
	"strings"

	"github.com/emiago/sipgo/sip"

	"github.com/freesbc/freesbc/config"
)

// plane is one of the two network sides the proxy straddles.
type plane int

const (
	planePublic plane = iota
	planePrivate
)

func (p plane) String() string {
	if p == planePublic {
		return "public"
	}
	return "private"
}

// side is everything needed to put a message on one plane: the address
// FreeSBC advertises there (Via sent-by, Contact, Record-Route) and the
// local socket the message must leave from.
//
// The local socket matters as much as the advertised address. A request
// toward a UDP phone must leave from the public listener the phone's NAT
// pinhole points at, and a request toward FreeSWITCH must leave from the
// private socket FreeSWITCH sends its own traffic to — otherwise responses
// come back to a socket nothing is listening on, or arrive from an address
// the far side does not recognise.
type side struct {
	plane     plane
	transport string // "udp", "ws" or "wss"
	advIP     netip.Addr
	advPort   int
	// laddr pins the outbound socket (see sipgo
	// TransportLayer.ClientRequestConnection: a request whose Laddr names
	// a bound listener reuses that listener's connection). It is left zero
	// for ws/wss, where the connection is found by the client's remote
	// address instead — a WebSocket is inbound-only, so there is exactly
	// one connection per client and it is already in the pool.
	laddr sip.Addr
}

// uri is the SBC's own URI on this side, as it appears in Record-Route,
// Via sent-by and Contact.
func (s side) uri() sip.Uri {
	u := sip.Uri{Host: s.advIP.String(), Port: s.advPort}
	if s.transport != "udp" {
		u.UriParams = sip.NewParams()
		u.UriParams.Add("transport", s.transport)
	}
	return u
}

// recordRoute is the loose-routing Record-Route value for this side.
func (s side) recordRoute() *sip.RecordRouteHeader {
	params := sip.NewParams()
	if s.transport != "udp" {
		params.Add("transport", s.transport)
	}
	params.Add("lr", "")
	return &sip.RecordRouteHeader{
		Address: sip.Uri{Host: s.advIP.String(), Port: s.advPort, UriParams: params},
	}
}

// via builds the Via header FreeSBC adds when forwarding onto this side.
// The branch is generated by the caller so it can be correlated.
//
// rport is requested on UDP only: it asks the next hop to report the
// source port it actually saw, which is what lets responses traverse the
// NAT a phone sits behind (RFC 3581). On WS there is no NAT to traverse —
// the connection is the path.
func (s side) via(branch string) *sip.ViaHeader {
	v := &sip.ViaHeader{
		ProtocolName:    "SIP",
		ProtocolVersion: "2.0",
		Transport:       strings.ToUpper(s.transport),
		Host:            s.advIP.String(),
		Port:            s.advPort,
		Params:          sip.NewParams(),
	}
	v.Params.Add("branch", branch)
	if s.transport == "udp" {
		v.Params.Add("rport", "")
	}
	return v
}

// topology is the resolved network model the proxy runs with, built once
// at startup from the config. Listener addresses cannot be changed under a
// running socket, so this is deliberately a snapshot rather than something
// re-read per request.
type topology struct {
	// public holds one side per enabled public transport.
	public map[string]side
	// private is the single FreeSWITCH-facing side.
	private side

	// upstream is FreeSWITCH's signaling address.
	upstream netip.AddrPort
	// upstreamHost is the address as configured, used for Destination.
	upstreamHost string

	// media advertised addresses.
	publicMediaIP  netip.Addr
	privateMediaIP netip.Addr
}

// buildTopology resolves the config into the runtime model. It performs
// no DNS: the upstream must be a literal address, so a poisoned resolver
// can never redirect the private leg.
func buildTopology(cfg *config.Config) (*topology, error) {
	host, portStr, err := net.SplitHostPort(cfg.SIP.Upstream.Address)
	if err != nil {
		return nil, err
	}
	ip, err := netip.ParseAddr(host)
	if err != nil {
		return nil, &configError{"sip.upstream.address must be a literal IP:port, got " + host}
	}
	port, err := strconv.Atoi(portStr)
	if err != nil {
		return nil, err
	}

	privIP := cfg.PrivateAdvertisedIP()
	t := &topology{
		public:       map[string]side{},
		upstream:     netip.AddrPortFrom(ip, uint16(port)),
		upstreamHost: cfg.SIP.Upstream.Address,
		private: side{
			plane:     planePrivate,
			transport: "udp",
			advIP:     privIP,
			advPort:   cfg.PrivateSIPAdvertisedPort(),
			laddr: sip.Addr{
				IP:   net.ParseIP(cfg.SIP.Private.Bind.Host),
				Port: cfg.SIP.Private.Bind.Port,
			},
		},
		publicMediaIP:  cfg.PublicRTPAdvertisedIP(),
		privateMediaIP: cfg.PrivateRTPAdvertisedIP(),
	}
	pubIP := cfg.PublicAdvertisedIP()
	for _, l := range cfg.PublicSIPListeners() {
		s := side{
			plane:     planePublic,
			transport: l.Transport,
			advIP:     pubIP,
			// Public listeners advertise the port they bind. A port
			// translation in front of FreeSBC would need its own config
			// field; there is deliberately none yet rather than a guess.
			advPort: l.Bind.Port,
		}
		if l.Transport == "udp" {
			s.laddr = sip.Addr{IP: net.ParseIP(l.Bind.Host), Port: l.Bind.Port}
		}
		t.public[l.Transport] = s
	}
	return t, nil
}

type configError struct{ msg string }

func (e *configError) Error() string { return "proxy: " + e.msg }

// publicSide returns the side for a client transport, falling back to the
// UDP side when the exact transport is not configured.
func (t *topology) publicSide(transport string) (side, bool) {
	transport = strings.ToLower(transport)
	if s, ok := t.public[transport]; ok {
		return s, true
	}
	return side{}, false
}

// isSelf reports whether a URI names one of FreeSBC's own signaling
// addresses. It is how the proxy recognises its own Record-Route values
// coming back as Route headers, and how it detects a loop.
//
// Only the host and port are compared; parameters are not, because a
// downstream element may legitimately add or reorder them.
func (t *topology) isSelf(u sip.Uri) bool {
	ip, err := netip.ParseAddr(u.Host)
	if err != nil {
		return false
	}
	ip = ip.Unmap()
	match := func(s side) bool {
		port := u.Port
		if port == 0 {
			port = 5060
		}
		return s.advIP == ip && s.advPort == port
	}
	if match(t.private) {
		return true
	}
	for _, s := range t.public {
		if match(s) {
			return true
		}
	}
	return false
}

// isSelfVia reports whether a Via header names one of FreeSBC's own
// signaling addresses. RFC 3261 §16.7 step 3 requires a proxy to check
// this before removing the top Via from a response — popping blindly
// destroys the requester's own Via whenever the far end sends a response
// that does not carry the full stack, which is not hypothetical: sofia's
// 100 Trying carries only the topmost Via.
func (t *topology) isSelfVia(v *sip.ViaHeader) bool {
	if v == nil {
		return false
	}
	ip, err := netip.ParseAddr(v.Host)
	if err != nil {
		return false
	}
	ip = ip.Unmap()
	port := v.Port
	if port == 0 {
		port = defaultPort(v.Transport)
	}
	if t.private.advIP == ip && t.private.advPort == port {
		return true
	}
	for _, s := range t.public {
		if s.advIP == ip && s.advPort == port {
			return true
		}
	}
	return false
}

// defaultPort is the conventional port for a transport, used when a Via
// omits one.
func defaultPort(transport string) int {
	switch strings.ToLower(transport) {
	case "tls", "wss":
		return 5061
	case "ws":
		return 80
	default:
		return 5060
	}
}

// fromUpstream reports whether a request arrived from FreeSWITCH. The
// transport source address is the only trustworthy signal — never a Via or
// From host, which the sender controls.
//
// Only the IP is compared, not the port: FreeSWITCH may source a request
// from an ephemeral port while still listening on its configured one.
func (t *topology) fromUpstream(src netip.Addr) bool {
	return src.Unmap() == t.upstream.Addr()
}
